---
job: extension
config:
  name: "lora_flux_schnell"
  process:
    - type: "sd_trainer"
      training_folder: "output"
      device: cuda:0
      trigger_word: "TOK"
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16 # precision to save
        save_every: 1750 # save every this many steps
        max_step_saves_to_keep: 1 # how many intermittent saves to keep
      datasets:
        - folder_path: "dataset"
          caption_ext: "txt"
          caption_dropout_rate: 0.05 # will drop out the caption 5% of time
          shuffle_tokens: false # shuffle caption order, split by commas
          cache_latents_to_disk: true # leave this true unless you know what you're doing
          resolution: [512, 768, 1024] # flux enjoys multiple resolutions
      train:
        batch_size: 1
        steps: 1750 # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false # probably won't work with flux
        gradient_checkpointing: true # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 1e-4
        ema_config:
          use_ema: true
          ema_decay: 0.99

        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "black-forest-labs/FLUX.1-schnell"
        assistant_lora_path: "ostris/FLUX.1-schnell-training-adapter" # Required for flux schnell training
        is_flux: true
        quantize: true # run 8bit mixed precision

      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 1750 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
          - "[trigger] holding a sign that says 'I LOVE PROMPTS!'"
        neg: "" # not used on flux
        seed: 42
        walk_seed: true
        guidance_scale: 1 # schnell does not do guidance
        sample_steps: 4 # 1 - 4 works well
meta:
  name: "[name]"
  version: "1.0"
