name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  push_to_dockerhub:
    name: Push to Dockerhub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set outputs
        id: git_commit_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Dockerhub
        run: |
          cog build -t ${{ secrets.DOCKERHUB_USERNAME }}/artsmart-flux-trainer:${{ steps.git_commit_short.outputs.sha_short }}
          cog push ${{ secrets.DOCKERHUB_USERNAME }}/artsmart-flux-trainer:${{ steps.git_commit_short.outputs.sha_short }}