name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "smartartdev/artsmart-flux-trainer"
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Set outputs
        id: git_commit_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}

      - name: Push to Docker HUB
        run: cog push ${{ secrets.DOCKERHUB_USERNAME }}/artsmart-flux-trainer:${{ steps.git_commit_short.outputs.sha_short }}
